### PR TITLE
Add Services Processor

### PR DESCRIPTION
**Pull request by SentryMan**
I heard you like annotation processors, so I made an annotation processor for the annotation processor for annotation processors. 

- Uses Services Processor to generate `META-INF/services/javax.annotation.processing.Processor` files for prism core
- Now avaje-prisms itself will automatically generate `META-INF/services/javax.annotation.processing.Processor` entries for detected annotation processors.

Services entries will be added if a concrete processor class has any of the following annotations:

- Any avaje prisms annotation
- `@SupportedAnnotationTypes`
- `@SupportedOptions`
- `@SupportedSourceVersion`

requires the spi lib to be deployed.

### CODE REVIEW

**Comment by xabolcs** [comment]
7vxu36

**Comment by SentryMan** [comment]
Hmm, maybe there's another way to go about this.

**Comment by SentryMan** [comment]
Yeah, I'm good with this

**Review by rbygrave — APPROVED** [review]
Looks good !!!

**Comment by SentryMan** [comment]
Alright then, I'll merge as soon as services gets deployed

**Pull request merged**
